// Generated by: pnpm db:types
// Run `pnpm db:types` to regenerate from your local Supabase instance.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      agent_traces: {
        Row: {
          agent: string
          cache_read_tokens: number | null
          cache_write_tokens: number | null
          created_at: string
          error: string | null
          estimated_cost_usd: number | null
          id: string
          input_tokens: number | null
          intent: string | null
          latency_ms: number | null
          model: string
          output_tokens: number | null
          prompt_version: string | null
          request_redacted: Json | null
          response_redacted: Json | null
          user_id: string | null
        }
        Insert: {
          agent: string
          cache_read_tokens?: number | null
          cache_write_tokens?: number | null
          created_at?: string
          error?: string | null
          estimated_cost_usd?: number | null
          id?: string
          input_tokens?: number | null
          intent?: string | null
          latency_ms?: number | null
          model: string
          output_tokens?: number | null
          prompt_version?: string | null
          request_redacted?: Json | null
          response_redacted?: Json | null
          user_id?: string | null
        }
        Update: {
          agent?: string
          cache_read_tokens?: number | null
          cache_write_tokens?: number | null
          created_at?: string
          error?: string | null
          estimated_cost_usd?: number | null
          id?: string
          input_tokens?: number | null
          intent?: string | null
          latency_ms?: number | null
          model?: string
          output_tokens?: number | null
          prompt_version?: string | null
          request_redacted?: Json | null
          response_redacted?: Json | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "agent_traces_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      cooking_multipliers: {
        Row: {
          created_at: string
          description: string | null
          fat_multiplier: number
          id: string
          kcal_multiplier: number
          method: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          fat_multiplier?: number
          id?: string
          kcal_multiplier?: number
          method: string
        }
        Update: {
          created_at?: string
          description?: string | null
          fat_multiplier?: number
          id?: string
          kcal_multiplier?: number
          method?: string
        }
        Relationships: []
      }
      correction_log: {
        Row: {
          corrected_value: string | null
          created_at: string
          field_corrected: string
          id: string
          meal_id: string
          original_value: string | null
          user_id: string
        }
        Insert: {
          corrected_value?: string | null
          created_at?: string
          field_corrected: string
          id?: string
          meal_id: string
          original_value?: string | null
          user_id: string
        }
        Update: {
          corrected_value?: string | null
          created_at?: string
          field_corrected?: string
          id?: string
          meal_id?: string
          original_value?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "correction_log_meal_id_fkey"
            columns: ["meal_id"]
            isOneToOne: false
            referencedRelation: "meals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "correction_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      ifct_foods: {
        Row: {
          aliases: string[]
          category: string | null
          code: string | null
          created_at: string
          id: string
          name: string
          notes: string | null
          per_100g: Json
          region: string | null
          typical_serving_g: number | null
        }
        Insert: {
          aliases?: string[]
          category?: string | null
          code?: string | null
          created_at?: string
          id?: string
          name: string
          notes?: string | null
          per_100g: Json
          region?: string | null
          typical_serving_g?: number | null
        }
        Update: {
          aliases?: string[]
          category?: string | null
          code?: string | null
          created_at?: string
          id?: string
          name?: string
          notes?: string | null
          per_100g?: Json
          region?: string | null
          typical_serving_g?: number | null
        }
        Relationships: []
      }
      meals: {
        Row: {
          b12_mcg_high: number | null
          b12_mcg_low: number | null
          calcium_mg_high: number | null
          calcium_mg_low: number | null
          carbs_g_high: number | null
          carbs_g_low: number | null
          confidence: number | null
          created_at: string
          fat_g_high: number | null
          fat_g_low: number | null
          fiber_g_high: number | null
          fiber_g_low: number | null
          id: string
          items: Json
          kcal_high: number
          kcal_lead: number
          kcal_low: number
          logged_at: string
          meal_slot: string | null
          message_id: string | null
          micro_flags: string[]
          omega3_g_high: number | null
          omega3_g_low: number | null
          photo_url: string | null
          potassium_mg_high: number | null
          potassium_mg_low: number | null
          preparation_assumptions: string | null
          protein_g_high: number | null
          protein_g_low: number | null
          safety_flags: string[]
          sodium_mg: number | null
          source_text: string | null
          updated_at: string
          user_confirmed: boolean
          user_corrected: boolean
          user_id: string
          vitamin_d_mcg_high: number | null
          vitamin_d_mcg_low: number | null
        }
        Insert: {
          b12_mcg_high?: number | null
          b12_mcg_low?: number | null
          calcium_mg_high?: number | null
          calcium_mg_low?: number | null
          carbs_g_high?: number | null
          carbs_g_low?: number | null
          confidence?: number | null
          created_at?: string
          fat_g_high?: number | null
          fat_g_low?: number | null
          fiber_g_high?: number | null
          fiber_g_low?: number | null
          id?: string
          items: Json
          kcal_high: number
          kcal_lead: number
          kcal_low: number
          logged_at?: string
          meal_slot?: string | null
          message_id?: string | null
          micro_flags?: string[]
          omega3_g_high?: number | null
          omega3_g_low?: number | null
          photo_url?: string | null
          potassium_mg_high?: number | null
          potassium_mg_low?: number | null
          preparation_assumptions?: string | null
          protein_g_high?: number | null
          protein_g_low?: number | null
          safety_flags?: string[]
          sodium_mg?: number | null
          source_text?: string | null
          updated_at?: string
          user_confirmed?: boolean
          user_corrected?: boolean
          user_id: string
          vitamin_d_mcg_high?: number | null
          vitamin_d_mcg_low?: number | null
        }
        Update: {
          b12_mcg_high?: number | null
          b12_mcg_low?: number | null
          calcium_mg_high?: number | null
          calcium_mg_low?: number | null
          carbs_g_high?: number | null
          carbs_g_low?: number | null
          confidence?: number | null
          created_at?: string
          fat_g_high?: number | null
          fat_g_low?: number | null
          fiber_g_high?: number | null
          fiber_g_low?: number | null
          id?: string
          items?: Json
          kcal_high?: number
          kcal_lead?: number
          kcal_low?: number
          logged_at?: string
          meal_slot?: string | null
          message_id?: string | null
          micro_flags?: string[]
          omega3_g_high?: number | null
          omega3_g_low?: number | null
          photo_url?: string | null
          potassium_mg_high?: number | null
          potassium_mg_low?: number | null
          preparation_assumptions?: string | null
          protein_g_high?: number | null
          protein_g_low?: number | null
          safety_flags?: string[]
          sodium_mg?: number | null
          source_text?: string | null
          updated_at?: string
          user_confirmed?: boolean
          user_corrected?: boolean
          user_id?: string
          vitamin_d_mcg_high?: number | null
          vitamin_d_mcg_low?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "meals_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "meals_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      memories: {
        Row: {
          content: string
          created_at: string
          expires_at: string | null
          id: string
          key: string
          layer: string
          updated_at: string
          user_id: string
          version: number
        }
        Insert: {
          content: string
          created_at?: string
          expires_at?: string | null
          id?: string
          key: string
          layer: string
          updated_at?: string
          user_id: string
          version?: number
        }
        Update: {
          content?: string
          created_at?: string
          expires_at?: string | null
          id?: string
          key?: string
          layer?: string
          updated_at?: string
          user_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "memories_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      memories_history: {
        Row: {
          changed_at: string
          changed_by: string
          content: string
          id: string
          key: string
          layer: string
          memory_id: string
          user_id: string
          version: number
        }
        Insert: {
          changed_at?: string
          changed_by?: string
          content: string
          id?: string
          key: string
          layer: string
          memory_id: string
          user_id: string
          version: number
        }
        Update: {
          changed_at?: string
          changed_by?: string
          content?: string
          id?: string
          key?: string
          layer?: string
          memory_id?: string
          user_id?: string
          version?: number
        }
        Relationships: []
      }
      messages: {
        Row: {
          agent_trace_id: string | null
          content: string
          created_at: string
          id: string
          in_reply_to: string | null
          kind: string
          metadata: Json
          photo_url: string | null
          role: string
          user_id: string
          voice_transcript: string | null
          voice_url: string | null
        }
        Insert: {
          agent_trace_id?: string | null
          content: string
          created_at?: string
          id?: string
          in_reply_to?: string | null
          kind: string
          metadata?: Json
          photo_url?: string | null
          role: string
          user_id: string
          voice_transcript?: string | null
          voice_url?: string | null
        }
        Update: {
          agent_trace_id?: string | null
          content?: string
          created_at?: string
          id?: string
          in_reply_to?: string | null
          kind?: string
          metadata?: Json
          photo_url?: string | null
          role?: string
          user_id?: string
          voice_transcript?: string | null
          voice_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_in_reply_to_fkey"
            columns: ["in_reply_to"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      nudge_queue: {
        Row: {
          acknowledged_at: string | null
          context_snapshot: Json | null
          created_at: string
          id: string
          kind: string
          message_id: string | null
          message_text: string | null
          push_sent_at: string | null
          scheduled_for: string
          skip_reason: string | null
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          acknowledged_at?: string | null
          context_snapshot?: Json | null
          created_at?: string
          id?: string
          kind: string
          message_id?: string | null
          message_text?: string | null
          push_sent_at?: string | null
          scheduled_for: string
          skip_reason?: string | null
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          acknowledged_at?: string | null
          context_snapshot?: Json | null
          created_at?: string
          id?: string
          kind?: string
          message_id?: string | null
          message_text?: string | null
          push_sent_at?: string | null
          scheduled_for?: string
          skip_reason?: string | null
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "nudge_queue_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "nudge_queue_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      nudge_schedules: {
        Row: {
          breakfast_check_at: string | null
          created_at: string
          dinner_check_at: string | null
          enabled: boolean
          encouragement: boolean
          end_of_day_at: string | null
          end_of_day_summary: boolean
          hydration_check_at: string | null
          hydration_reminders: boolean
          lunch_check_at: string | null
          max_per_day: number
          meal_check_ins: boolean
          min_gap_minutes: number
          updated_at: string
          user_id: string
        }
        Insert: {
          breakfast_check_at?: string | null
          created_at?: string
          dinner_check_at?: string | null
          enabled?: boolean
          encouragement?: boolean
          end_of_day_at?: string | null
          end_of_day_summary?: boolean
          hydration_check_at?: string | null
          hydration_reminders?: boolean
          lunch_check_at?: string | null
          max_per_day?: number
          meal_check_ins?: boolean
          min_gap_minutes?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          breakfast_check_at?: string | null
          created_at?: string
          dinner_check_at?: string | null
          enabled?: boolean
          encouragement?: boolean
          end_of_day_at?: string | null
          end_of_day_summary?: boolean
          hydration_check_at?: string | null
          hydration_reminders?: boolean
          lunch_check_at?: string | null
          max_per_day?: number
          meal_check_ins?: boolean
          min_gap_minutes?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "nudge_schedules_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          last_used_at: string | null
          p256dh: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          last_used_at?: string | null
          p256dh: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          last_used_at?: string | null
          p256dh?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limits: {
        Row: {
          bucket: string
          id: string
          request_count: number
          user_id: string
          window_start: string
        }
        Insert: {
          bucket: string
          id?: string
          request_count?: number
          user_id: string
          window_start: string
        }
        Update: {
          bucket?: string
          id?: string
          request_count?: number
          user_id?: string
          window_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "rate_limits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      source_multipliers: {
        Row: {
          created_at: string
          description: string | null
          fat_multiplier: number
          id: string
          kcal_multiplier: number
          sodium_multiplier: number
          source: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          fat_multiplier?: number
          id?: string
          kcal_multiplier?: number
          sodium_multiplier?: number
          source: string
        }
        Update: {
          created_at?: string
          description?: string | null
          fat_multiplier?: number
          id?: string
          kcal_multiplier?: number
          sodium_multiplier?: number
          source?: string
        }
        Relationships: []
      }
      user_features: {
        Row: {
          avg_daily_kcal_7d: number | null
          avg_daily_protein_7d: number | null
          avg_daily_water_7d: number | null
          correction_count: number
          created_at: string
          current_streak_days: number | null
          daily_water_target_ml: number | null
          days_logged_last_30: number | null
          eat_out_per_week: number | null
          home_oil_preference: string | null
          longest_streak_days: number | null
          meal_variance: string | null
          nudge_tone: string | null
          portion_bias: number | null
          portion_confidence: string | null
          protein_target_hit_rate_7d: number | null
          restaurant_oil_assumption: string | null
          snacks_typical: string | null
          track_hydration: boolean | null
          typical_breakfast_time: string | null
          typical_dinner_time: string | null
          typical_lunch_time: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          avg_daily_kcal_7d?: number | null
          avg_daily_protein_7d?: number | null
          avg_daily_water_7d?: number | null
          correction_count?: number
          created_at?: string
          current_streak_days?: number | null
          daily_water_target_ml?: number | null
          days_logged_last_30?: number | null
          eat_out_per_week?: number | null
          home_oil_preference?: string | null
          longest_streak_days?: number | null
          meal_variance?: string | null
          nudge_tone?: string | null
          portion_bias?: number | null
          portion_confidence?: string | null
          protein_target_hit_rate_7d?: number | null
          restaurant_oil_assumption?: string | null
          snacks_typical?: string | null
          track_hydration?: boolean | null
          typical_breakfast_time?: string | null
          typical_dinner_time?: string | null
          typical_lunch_time?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          avg_daily_kcal_7d?: number | null
          avg_daily_protein_7d?: number | null
          avg_daily_water_7d?: number | null
          correction_count?: number
          created_at?: string
          current_streak_days?: number | null
          daily_water_target_ml?: number | null
          days_logged_last_30?: number | null
          eat_out_per_week?: number | null
          home_oil_preference?: string | null
          longest_streak_days?: number | null
          meal_variance?: string | null
          nudge_tone?: string | null
          portion_bias?: number | null
          portion_confidence?: string | null
          protein_target_hit_rate_7d?: number | null
          restaurant_oil_assumption?: string | null
          snacks_typical?: string | null
          track_hydration?: boolean | null
          typical_breakfast_time?: string | null
          typical_dinner_time?: string | null
          typical_lunch_time?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_features_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          age: number | null
          allergies: string[]
          city: string | null
          conditions: string[]
          conditions_other: string | null
          created_at: string
          daily_carbs_target: number | null
          daily_fat_target: number | null
          daily_fiber_target: number | null
          daily_kcal_target: number | null
          daily_protein_target: number | null
          daily_water_target_ml: number | null
          dietary_pattern: string | null
          dislikes: string | null
          eating_context: string | null
          gender: string | null
          goal_target_kg: number | null
          goal_timeline_weeks: number | null
          height_cm: number | null
          meal_times: Json
          medications: string | null
          primary_goal: string | null
          updated_at: string
          user_id: string
          weight_kg: number | null
        }
        Insert: {
          age?: number | null
          allergies?: string[]
          city?: string | null
          conditions?: string[]
          conditions_other?: string | null
          created_at?: string
          daily_carbs_target?: number | null
          daily_fat_target?: number | null
          daily_fiber_target?: number | null
          daily_kcal_target?: number | null
          daily_protein_target?: number | null
          daily_water_target_ml?: number | null
          dietary_pattern?: string | null
          dislikes?: string | null
          eating_context?: string | null
          gender?: string | null
          goal_target_kg?: number | null
          goal_timeline_weeks?: number | null
          height_cm?: number | null
          meal_times?: Json
          medications?: string | null
          primary_goal?: string | null
          updated_at?: string
          user_id: string
          weight_kg?: number | null
        }
        Update: {
          age?: number | null
          allergies?: string[]
          city?: string | null
          conditions?: string[]
          conditions_other?: string | null
          created_at?: string
          daily_carbs_target?: number | null
          daily_fat_target?: number | null
          daily_fiber_target?: number | null
          daily_kcal_target?: number | null
          daily_protein_target?: number | null
          daily_water_target_ml?: number | null
          dietary_pattern?: string | null
          dislikes?: string | null
          eating_context?: string | null
          gender?: string | null
          goal_target_kg?: number | null
          goal_timeline_weeks?: number | null
          height_cm?: number | null
          meal_times?: Json
          medications?: string | null
          primary_goal?: string | null
          updated_at?: string
          user_id?: string
          weight_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "user_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          display_name: string | null
          estimation_preference: string
          id: string
          nudge_tone: string
          nudges_enabled: boolean
          onboarded_at: string | null
          quiet_hours_end: string
          quiet_hours_start: string
          timezone: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          estimation_preference?: string
          id: string
          nudge_tone?: string
          nudges_enabled?: boolean
          onboarded_at?: string | null
          quiet_hours_end?: string
          quiet_hours_start?: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          estimation_preference?: string
          id?: string
          nudge_tone?: string
          nudges_enabled?: boolean
          onboarded_at?: string | null
          quiet_hours_end?: string
          quiet_hours_start?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      water_logs: {
        Row: {
          amount_ml: number
          created_at: string
          id: string
          logged_at: string
          message_id: string | null
          user_id: string
        }
        Insert: {
          amount_ml: number
          created_at?: string
          id?: string
          logged_at?: string
          message_id?: string | null
          user_id: string
        }
        Update: {
          amount_ml?: number
          created_at?: string
          id?: string
          logged_at?: string
          message_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "water_logs_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "water_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      daily_totals: {
        Row: {
          b12_mcg: number | null
          calcium_mg: number | null
          carbs_g: number | null
          day: string | null
          fat_g: number | null
          fiber_g: number | null
          kcal_high_total: number | null
          kcal_low_total: number | null
          kcal_total: number | null
          meal_count: number | null
          omega3_g: number | null
          potassium_mg: number | null
          protein_g: number | null
          sodium_mg: number | null
          user_id: string | null
          vitamin_d_mcg: number | null
        }
        Relationships: [
          {
            foreignKeyName: "meals_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_water: {
        Row: {
          day: string | null
          log_count: number | null
          total_ml: number | null
          user_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "water_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      weekly_totals: {
        Row: {
          avg_b12_mcg: number | null
          avg_calcium_mg: number | null
          avg_carbs_g: number | null
          avg_fat_g: number | null
          avg_fiber_g: number | null
          avg_kcal: number | null
          avg_omega3_g: number | null
          avg_potassium_mg: number | null
          avg_protein_g: number | null
          avg_vitamin_d_mcg: number | null
          days_logged: number | null
          total_meals: number | null
          user_id: string | null
          week_start: string | null
        }
        Relationships: [
          {
            foreignKeyName: "meals_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      cleanup_rate_limits: { Args: never; Returns: undefined }
      get_daily_totals: {
        Args: { p_end: string; p_start: string }
        Returns: {
          b12_mcg: number | null
          calcium_mg: number | null
          carbs_g: number | null
          day: string | null
          fat_g: number | null
          fiber_g: number | null
          kcal_high_total: number | null
          kcal_low_total: number | null
          kcal_total: number | null
          meal_count: number | null
          omega3_g: number | null
          potassium_mg: number | null
          protein_g: number | null
          sodium_mg: number | null
          user_id: string | null
          vitamin_d_mcg: number | null
        }[]
        SetofOptions: {
          from: "*"
          to: "daily_totals"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      get_daily_water: {
        Args: { p_end: string; p_start: string }
        Returns: {
          day: string | null
          log_count: number | null
          total_ml: number | null
          user_id: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "daily_water"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      get_weekly_totals: {
        Args: { p_end: string; p_start: string }
        Returns: {
          avg_b12_mcg: number | null
          avg_calcium_mg: number | null
          avg_carbs_g: number | null
          avg_fat_g: number | null
          avg_fiber_g: number | null
          avg_kcal: number | null
          avg_omega3_g: number | null
          avg_potassium_mg: number | null
          avg_protein_g: number | null
          avg_vitamin_d_mcg: number | null
          days_logged: number | null
          total_meals: number | null
          user_id: string | null
          week_start: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "weekly_totals"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      increment_rate_limit: {
        Args: {
          p_bucket: string
          p_limit: number
          p_user_id: string
          p_window_minutes: number
        }
        Returns: {
          allowed: boolean
          current_count: number
          reset_at: string
        }[]
      }
      refresh_analytics_views: { Args: never; Returns: undefined }
      select_nudge_candidates: {
        Args: never
        Returns: {
          breakfast_check_at: string
          dinner_check_at: string
          display_name: string
          end_of_day_at: string
          hydration_check_at: string
          lunch_check_at: string
          max_per_day: number
          min_gap_minutes: number
          nudge_tone: string
          quiet_hours_end: string
          quiet_hours_start: string
          timezone: string
          user_id: string
        }[]
      }
      select_users_for_consolidation: {
        Args: never
        Returns: {
          user_id: string
        }[]
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
